### ISSUE TITLE
Some weights are negative when running gawdis, w.type= "analytic"

### ISSUE THREAD

**Issue by liamjakehughes** [pavel-fibich/gawdis#1]
Hi!

So I have been trying to create a gawer dissimilarity matrix with w.type "analytic". My data set has four trait types, one continuous, one categorical, one multi-choice binary (three levels) and one fuzzy (four levels). I have grouped the different traits following your tutorial, as well as setting the appropriate fuzzy settings. However, after running through all four traits I get the following error message: 

"Error in if (any(w < 0) & (!silent)) warning("Some weights are negative! Try to remove the corresponding trait from the analysis or re-run the function with w.type='optimized'") : 
  missing value where TRUE/FALSE needed". 

I have double checked my dataset and there are no NAs or negative values. I have also tried running gawdis with different subsets of the traits and can't work out what the issue. Any idea what might be causing this? 

Kind regard,
Liam

**Comment by pavel-fibich** [comment]
Hi Liam,
it looks like that w (vector with weights) is empty. Could you sent me any example how to reproduce the problem, and/or how do you call the gawdis with some summary() on your input dataset?
Best, Pavel

**Comment by jguerber** [comment]
Hello,

First of all thanks for this implementation !

I was working on the same type on data than Liam and encountered the same error. It can be reproduced with the dummy data provided by the `FD` package : 

```r
library(dplyr)
library(FD)

dummy$trait[,c(2,4,6,8)] %>% # non-NA columns
  gawdis::gawdis(
    groups = c(1,2,3,3),
    w.type = "analytic"
  ) # throws the same error
```

It looks like there is an empty vector issue when the trait data is a mix of grouped and non-grouped variables. I'm looking into it in a fork but I might not be familiar enough with the analytical method to suggest a rigorous fix :)

Hope this helps,
Josquin

**Comment by pavel-fibich** [comment]
Hi Josquin,
thank you for reporting the problem. There was really a bug in an analytic branch with handling multiple groups. I improved the analytic part of computation and pushed new code on github. If you can check it on your data it will be great, then I will forward to CRAN.
Best, Pavel

**Comment by jguerber** [comment]
Hi, bug fixed :)
The new version works on my data and on the dummy example.

Thank you for the quick reply and fix !
