### ISSUE TITLE
Error in if (object@run >= run) break : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by javimorente** [pavel-fibich/gawdis#2]
Dear developers of the gawdis R package.
First of all, thanks for creating this great package/function. It´s very useful.
I´m trying to use gawdis() with databases combining qualitative and quantitative functional traits in the context of plant communities.
In some of these communities (defined as plots), the following error appears:
Error in if (object@run >= run) break : 
  missing value where TRUE/FALSE needed

Do you know why this error is appearing in some plots and not others? 
Could this be related to the fact that in some cases I have many NAs in a trait (column) and/or row (species) and only one level of the qualitative trait is present?

Any suggestion of what is happening will be of great help.
Thank you in advance!

**Comment by pavel-fibich** [comment]
Hi, it is great that you are using gawdis.
The error looks like one from GA package (used by gawdis), but it is hard to help without reproducible input data. I would try, you already suggested that, to remove some traits having only one level (such trait will not help) or traits having many NAs.

**Comment by javimorente** [comment]
Hi, sorry for the delayed answer... 
Finally, I tried several solutions and apparently, you were right and it was a problem with traits having many NAs. I solved the problem by recoding and unifying some traits in a single one and then capturing more information in one trait and so removing NAs. Thank you for the reply!
